wandb:
  use_wandb: False
  project: "simca"
  entity: "pavis-hsp"
  display_name: ${now:%Y-%m-%d}/${now:%H-%M-%S}

model:
  model_name: "Salesforce/blip2-opt-2.7b"
  text_input: False
  model_max_length: 512

dataset:
  train_csv: "/media/tapicella/Data/data/gibson_randomGoal_coca_mask2former_train.csv"
  val_csv: "/media/tapicella/Data/data/gibson_randomGoal_coca_mask2former_train.csv"
  use_augmentation: False

training_setup:
  multigpu: False
  seed: 44
  batch_size: 2
  learning_rate: 0.0001
  num_workers: 0
  epochs: 10
  save_interval: 1
  early_stopping: True
  patience: 3
  use_triplet: True  # If True, the actual batch size will be batch_size*3
  use_negative: False
