wandb:
  use_wandb: False
  project: "..."
  entity: "..."
  display_name: ${now:%Y-%m-%d}/${now:%H-%M-%S}

model:
  model_name: "Salesforce/blip2-opt-2.7b"
  text_input: False
  model_max_length: 512

dataset:
  train_csv: "..."
  val_csv: "..."
  use_augmentation: True

training_setup:
  multigpu: False
  seed: 1
  batch_size: 2
  learning_rate: 0.0001
  num_workers: 0
  epochs: 10
  save_interval: 1
  early_stopping: True
  patience: 3
  use_triplet: True  # If True, the actual batch size will be batch_size*3
  triplet_loss_weight: 0.5
